- name: Install components
  hosts: "{{ component }}"
  become: yes
  roles:
    - "{{ component }}"
  vars:
    component:
      - mysql
      - backend
      - frontend
  loop: "{{ component }}"