- name: setting server name
  ansible.builtin.shell: set-hostname "{{ component }}"

- name: installing {{component }} server
  ansible.builtin.package:
    name: mysql-server
    state: present
   

- name: enable {{component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: installing dependecies for mysql
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: present


- name:   setting root password
  community.mysql.mysql_db:
    name: expensedb
    login_user: root
    login_password: ExpenseApp@1


