- name: setting server name
  ansible.builtin.shell: set-hostname "{{component}}-{{env}}"

- name: installing {{component }} server
  ansible.builtin.yum:
    name: mysql-server
    state: present
   

- name: enable {{component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

# - name: installing dependecies for mysql
#   ansible.builtin.yum:
#     name: python3-PyMySQL
#     state: present


- name: reset passworf for root
  ansible.builtin.shell: mysql_secure_installation --set-root-pass "{{ lookup('hashi_vault', '/v1/expense-dev/data/mysql:mysql_pass', token=vault_token, url=vault_url, validate_certs=False) }}"



