- name: setting server name
  ansible.builtin.shell: set-hostname "{{ component }}"

- name: installing {{component }} server
  ansible.builtin.package:
    name: mysql-server
    state: present
   

- name: enable {{component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: installing dependecies for mysql
  ansible.builtin.yum:
    name: python3-PyMySQL
    state: present


- name: Try to create database as root/nopassword first. If not allowed, pass the credentials
  community.mysql.mysql_db:
    check_implicit_admin: true
    login_user: root
    login_password: ExpenseApp@1
    name: all
    state: present




