- name: Run tasks/pre-req.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req

- name: installing {{component }} server
  ansible.builtin.yum:
    name: mysql-server
    state: present
   

- name: enable {{component }} service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

# - name: installing dependecies for mysql
#   ansible.builtin.yum:
#     name: python3-PyMySQL
#     state: present

- name: reset passworf for root
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1


# - name: reset passworf for root
#   ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ secrets.mysql_pass }}



