- name: setting server name
  ansible.builtin.shell: set-hostname "{{ component }}"
- name: installing {{component }} server
  ansible.builtin.package:
    name: mysql-server
    state: present
    become: yes

- name: enable {{component }} service
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes

- name:   setting root password
  mysql_user:
    name: root
    password: ExpenseApp@1


