component: ""
SQL_HOST: "mysql-{{env}}.eternallearnings.shop"

secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/expense-dev/data/mysql token=hvs.3emIVhWDWFRTogKqmmXvkPe3 url=https://3.234.224.238:8200 validate_certs=False') }}"
