component: ""
SQL_HOST: "mysql-{{env}}.eternallearnings.shop"
 
secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{env}}/data/MYSQL_CRED token={{ token }} url=https://vault.eternallearnings.shop:8200 validate_certs=False') }}"
