- name: setting up server name for this instance
  ansible.builtin.shell: set-hostname "{{component}}-{{env}}"

- name: install hvac for secrets
  ansible.builtin.pip:
    name: hvac
    state: present
    executable: /usr/bin/pip3.11                      